name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Backend Dependencies
        working-directory: ./multi-02-finished/backend
        run: npm install

      - name: Install Frontend Dependencies
        working-directory: ./multi-02-finished/frontend
        run: npm install

      - name: Build Frontend
        working-directory: ./multi-02-finished/frontend
        run: npm run build
